apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: heb-transcription-worker-hpa
  namespace: heb-transcription
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heb-transcription-worker
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
